export default {
    COUNTER_INCREMENT: 'COUNTER_INCREMENT',
    COUNTER_DECREMENT: 'COUNTER_DECREMENT',
    COUNTER_INCREMENT_ASYNC: 'COUNTER_INCREMENT_ASYNC',
    COUNTER_DECREMENT_ASYNC: 'COUNTER_DECREMENT_ASYNC',
}
